// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAVZG5cUQRwhwVY1kHGC8s0l6X_W0wpHSw",
      authDomain: "alumni-connect-mca.firebaseapp.com",
      projectId: "alumni-connect-mca",
      storageBucket: "alumni-connect-mca.firebasestorage.app",
      messagingSenderId: "99609905664",
      appId: "1:99609905664:web:ffc0b8bb53c82e0969e6e5",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSOgkenEBcD3peqiSl1Ge2LX1vWe4IvFU',
    appId: '1:99609905664:android:9ed49ad581f9673269e6e5',
    messagingSenderId: '99609905664',
    projectId: 'alumni-connect-mca',
    storageBucket: 'alumni-connect-mca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPaLwpHoXNuJQfXhHZ1NZrgVx_dSY_Glo',
    appId: '1:99609905664:ios:5f06d8a8e9df458a69e6e5',
    messagingSenderId: '99609905664',
    projectId: 'alumni-connect-mca',
    storageBucket: 'alumni-connect-mca.firebasestorage.app',
    iosBundleId: 'com.balaji.alumniconnectmca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPaLwpHoXNuJQfXhHZ1NZrgVx_dSY_Glo',
    appId: '1:99609905664:ios:5f06d8a8e9df458a69e6e5',
    messagingSenderId: '99609905664',
    projectId: 'alumni-connect-mca',
    storageBucket: 'alumni-connect-mca.firebasestorage.app',
    iosBundleId: 'com.balaji.alumniconnectmca',
  );
}